services:
  postgres:
    image: postgres
    env_file:
      - .env-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cache:/data 

volumes:
  postgres_data:
  cache: